name: Package Application

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  package-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install fyne.io/tools/cmd/fyne@latest
      - run: export PATH="$HOME/go/bin:$PATH"
      - uses: android-actions/setup-android@v3
      - run: go mod tidy
      - run: mkdir -p build && $HOME/go/bin/fyne package -os android --app-id com.flaggedit.app --icon assets/favicon.svg --name flagged-it --output build/flagged-it.apk ./cmd
      - uses: actions/upload-artifact@v4
        with:
          name: flagged-it-android
          path: build/flagged-it.apk

  package-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install fyne.io/tools/cmd/fyne@latest
      - run: export PATH="$HOME/go/bin:$PATH"
      - run: go mod tidy
      - run: mkdir -p build && $HOME/go/bin/fyne package -os ios --app-id com.flaggedit.app --icon assets/favicon.svg --name flagged-it-${{ matrix.arch }} --output build/flagged-it-${{ matrix.arch }}.app ./cmd
      - uses: actions/upload-artifact@v4
        with:
          name: flagged-it-ios-${{ matrix.arch }}
          path: build/flagged-it-${{ matrix.arch }}.app

  package-ios-simulator:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install fyne.io/tools/cmd/fyne@latest
      - run: export PATH="$HOME/go/bin:$PATH"
      - run: go mod tidy
      - run: mkdir -p build && $HOME/go/bin/fyne package -os iossimulator --app-id com.flaggedit.app --icon assets/favicon.svg --name flagged-it-sim-${{ matrix.arch }} --output build/flagged-it-sim-${{ matrix.arch }}.app ./cmd
      - uses: actions/upload-artifact@v4
        with:
          name: flagged-it-ios-simulator-${{ matrix.arch }}
          path: build/flagged-it-sim-${{ matrix.arch }}.app
